const state={view:'overview',token:localStorage.getItem('allmusic_dashboard_token')||'',data:{}};
const content=document.querySelector('#content');
const titles={overview:['RESUMEN','Panel de control'],users:['USUARIOS','Gestión de usuarios'],library:['BIBLIOTECA','Biblioteca de Telegram'],activity:['ACTIVIDAD','Solicitudes recientes'],system:['SISTEMA','Rendimiento y configuración']};
async function api(path,options={}){const headers={...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});if(response.status===401||response.status===503){document.querySelector('#auth-dialog').showModal();throw new Error('Autenticación requerida');}if(!response.ok)throw new Error(await response.text());return response.json()}
const esc=value=>String(value??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const metric=(label,value,note='')=>`<article class="card"><span class="metric-label">${label}</span><strong class="metric-value">${value}</strong><span class="metric-note">${note}</span></article>`;
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
async function overview(){const data=await api('/api/stats');const s=data.summary;const max=Math.max(1,...data.top.map(x=>x[1]));content.innerHTML=`<div class="metrics">${metric('Usuarios',s.total_users,'registrados')}${metric('Descargas',s.total_downloads,'históricas')}${metric('Caché',s.cached_songs,`${s.cache_rate}% reutilización`)}${metric('Fallos',s.failed_downloads,'registrados')}</div><div class="grid-2"><section class="panel"><h2>Top global</h2><div class="bars">${data.top.map(([title,count],i)=>`<div><div class="bar-label"><span>${i+1}. ${esc(title)}</span><strong>${count}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${count/max*100}%"></div></div></div>`).join('')||'<div class="empty">Sin descargas todavía</div>'}</div></section><section class="panel"><h2>Estado operacional</h2><div id="overview-system" class="system-grid"></div></section></div>`;const sys=await api('/api/system');document.querySelector('#overview-system').innerHTML=systemItems(sys)}
function filtered(items,q,fields){q=q.toLowerCase();return items.filter(x=>fields.some(f=>String(x[f]??'').toLowerCase().includes(q)))}
async function users(){const data=await api('/api/users');state.data.users=data;renderUsers(data)}
function renderUsers(data){content.innerHTML=`<div class="toolbar"><input id="search-users" placeholder="Buscar ID o usuario…"></div>${table(['ID','Usuario','Descargas','Última actividad','Estado'],data.map(u=>`<tr data-user="${u.user_id}"><td>${u.user_id}</td><td>@${esc(u.username||'sin_usuario')}</td><td>${u.total_downloads}</td><td>${esc(u.last_download_date)}</td><td><span class="chip ${u.is_banned?'bad':'good'}">${u.is_banned?'Baneado':'Activo'}</span></td></tr>`))}`;document.querySelector('#search-users').oninput=e=>renderUsers(filtered(state.data.users,e.target.value,['user_id','username']));document.querySelectorAll('[data-user]').forEach(row=>row.onclick=()=>userDetail(row.dataset.user))}
async function userDetail(id){const data=await api(`/api/users/${id}`);const u=data.info;document.querySelector('#detail-content').innerHTML=`<h2>@${esc(u.username||'sin_usuario')}</h2><p>ID: <code>${u.user_id}</code> · ${u.total_downloads} descargas</p><button id="toggle-ban" class="button ${u.is_banned?'':'ghost'}">${u.is_banned?'Desbanear':'Banear'}</button><h3>Historial</h3>${table(['Pista','Fecha','Origen'],data.history.map(h=>`<tr><td>${esc(h.title)}</td><td>${esc(h.date)}</td><td>${h.cache_hit?'Caché':'Nueva'}</td></tr>`))}`;document.querySelector('#detail-dialog').showModal();document.querySelector('#toggle-ban').onclick=async()=>{await api(`/api/users/${id}/ban`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({banned:!u.is_banned})});document.querySelector('#detail-dialog').close();users()}}
async function library(){const data=await api('/api/songs');state.data.songs=data;renderLibrary(data)}
function renderLibrary(data){content.innerHTML=`<div class="toolbar"><input id="search-songs" placeholder="Buscar canción o ID…"></div>${table(['Título','YouTube ID','Descargas','Último uso'],data.map(s=>`<tr><td>${esc(s.title)}</td><td><code>${s.video_id}</code></td><td>${s.download_count}</td><td>${esc(s.last_used_at)}</td></tr>`))}`;document.querySelector('#search-songs').oninput=e=>renderLibrary(filtered(state.data.songs,e.target.value,['title','video_id']))}
async function activity(){const data=await api('/api/history');content.innerHTML=table(['Usuario','Pista','Fecha','Entrega'],data.map(h=>`<tr><td>${esc(h.username||h.user_id)}</td><td>${esc(h.title)}</td><td>${esc(h.date)}</td><td><span class="chip ${h.cache_hit?'good':''}">${h.cache_hit?'Caché':'Descarga'}</span></td></tr>`))}
function systemItems(s){return Object.entries({Bot:s.bot_online?'Online':'Offline','Descargas activas':s.active_downloads,'En cola':s.queue_depth,'Sistema':s.platform,'yt-dlp':s.yt_dlp_version,'Marca':s.brand}).map(([k,v])=>`<div class="system-item"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}
async function system(){const data=await api('/api/system');content.innerHTML=`<section class="panel"><h2>Estado del servicio</h2><div class="system-grid">${systemItems(data)}</div></section><section class="panel" style="margin-top:18px"><h2>Controles</h2><p class="metric-label">Las acciones destructivas y reinicios permanecen en Telegram para reducir la superficie de ataque. El dashboard permite administrar baneos y consultar todo el sistema.</p></section>`}
async function render(){const [section,title]=titles[state.view];document.querySelector('#section-name').textContent=section;document.querySelector('#page-title').textContent=title;content.innerHTML='<div class="loading">Cargando datos…</div>';try{await ({overview,users,library,activity,system}[state.view])()}catch(error){if(!/Autenticación/.test(error.message))content.innerHTML=`<div class="empty">${esc(error.message)}</div>`}}
async function health(){try{const h=await api('/api/health');document.querySelector('#status-dot').classList.toggle('online',h.bot);document.querySelector('#bot-status').textContent=h.bot?'Bot online':'Bot offline'}catch{document.querySelector('#bot-status').textContent='Sin conexión'}}
document.querySelectorAll('#nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');state.view=button.dataset.view;render()});
document.querySelector('#refresh').onclick=render;document.querySelector('#save-token').onclick=()=>{state.token=document.querySelector('#token-input').value.trim();localStorage.setItem('allmusic_dashboard_token',state.token);setTimeout(render)};
health();render();setInterval(health,30000);
