# Cambia la primera línea por esta (es un poco más pesada pero trae TODO lo necesario)


FROM python:3.10

# Actualiza e instala explícitamente
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "main.py"]